name: Deploy to EC2 (Production)

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: yarn install
    
    - name: Build and Export the project
      env:
        NEXT_PUBLIC_BASE_PATH: '/'
        NEXT_PUBLIC_ASSET_PREFIX: '/'
      run: yarn build
    
    - name: Deploy to EC2 (Production)
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -o StrictHostKeyChecking=no -i private_key -r .next ${USER}@${HOST}:/var/www/lppi-dashboard
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          sudo chown -R www-data:www-data /var/www/lppi-dashboard &&
          sudo systemctl restart apache2
        '